#!/bin/bash

# move into working directory
cd info

read -p "Make sure to include administrators in users.authorized!" yn
vi users.authorized

# Saves details of any unauthorized users before deletion
fgrep -v -f users.authorized /etc/passwd | grep :10[0-9][0-9] > users.deleted

# Auto-deletes any unauthorized users present on the system
while read LINE
do
    for i in $(seq 1 ${#LINE})
    do
        if [ ${LINE:$i:1} = ":" ]
        then
            	sudo deluser ${LINE:0:$i} 
	    	break
        fi
    done
done < users.deleted
